export default {
  data() {
    return {
      portfolios: [
        {
          id: 1,
          img: require(`@/assets/images/portfolio/project-1.jpg`),
          title: "PINBALL PROJECT",
          project: "Competitive Pinball 1vs1",
          client: "ENJMIN",
          language: "C#, Unity, C++, Arduino",
          preview: "Pinball Game",
          previewLink: "https://lucasjaouen.itch.io/pingoal",
        },
        // {
        //   id: 1,
        //   img: require(`@/assets/images/portfolio/project-1.jpg`),
        //   title: "WEBSITE PROJECT",
        //   project: "Parallax Website",
        //   client: "Universe Secrets",
        //   language: "Vue, HTML, CSS, JS",
        //   preview: "UniverseSecretsBlog",
        //   previewLink: "https://universesecrets.github.io/galaxy_blog/",
        // },
        {
          id: 2,
          img: require(`@/assets/images/portfolio/project-2.jpg`),
          title: "ARDUINO PROJECT",
          project: "Electronic Dice",
          client: "ENJMIN",
          language: "C++",
          preview: "Dé électronique",
          previewLink: "https://youtube.com/shorts/31h9lt00-Fs?feature=share",
        },
        {
          id: 3,
          img: require(`@/assets/images/portfolio/project-3.jpg`),
          title: "Multimedia PROJECT",
          project: "Immersive Intercative Story",
          client: "CONSTANT Thomas",
          language: "Construct 2",
          preview: "DABOX",
          previewLink: "https://landrygd.itch.io/dabox",
        },
        // {
        //   id: 4,
        //   img: require(`@/assets/images/portfolio/project-4.jpg`),
        //   title: "DRIBBBLE PROJECT",
        //   project: "Project Shoot",
        //   client: "dribbble",
        //   language: "React",
        //   preview: "www.dribbble.com",
        //   previewLink: "https://dribbble.com/ib-themes",
        // },
        {
          id: 5,
          img: require(`@/assets/images/portfolio/project-5.jpg`),
          title: "Neuroscience PROJECT",
          project: "Become aware of Cognitive Biases",
          client: "DE BOUCAUD Brigitte",
          language: "C#, Unity",
          preview: "Specifications",
          previewLink: "https://docs.google.com/document/d/1cnkaqck5LnHbnczMoSMpm06ZGcQv03sz3QyMxM_o79c/edit?usp=sharing",
        },
        // {
        //   id: 6,
        //   img: require(`@/assets/images/portfolio/project-6.jpg`),
        //   title: "SAAS PROJECT",
        //   project: "Web Application",
        //   client: "Themeforest",
        //   language: "HTML, CSS, ReactJs",
        //   preview: "www.themeforest.com",
        //   previewLink:
        //     "https://themeforest.net/item/deski-saas-software-react-template/33799794",
        // },
        // {
        //   id: 7,
        //   img: require(`@/assets/images/portfolio/project-7.jpg`),
        //   title: "MOCKUP PROJECT",
        //   project: "Website",
        //   client: "Pexels",
        //   language: "Adobe Photoshop",
        //   preview: "www.pexels.com",
        //   previewLink: "https://www.pexels.com/",
        // },
        // {
        //   id: 8,
        //   img: require(`@/assets/images/portfolio/project-8.jpg`),
        //   title: "FACEBOOK PROJECT",
        //   project: "Shoot",
        //   client: "Facebook",
        //   language: "Reactjs",
        //   preview: "www.facebook.com",
        //   previewLink: "https://www.facebook.com/ibthemes",
        // },
        // {
        //   id: 9,
        //   img: require(`@/assets/images/portfolio/project-9.jpg`),
        //   title: "LINKEDIN PROJECT",
        //   project: "Website",
        //   client: "Linkedin",
        //   language: "Vue 3",
        //   preview: "www.linkedin.com",
        //   previewLink:
        //     "https://www.linkedin.com/in/ib-themes-company-469408207/recent-activity/shares/",
        // },
      ],
    };
  },
};
